Repository libopenstorage/stork, pull requests merged in 2019-10, with the labels that each got.

#483 Some optimizations for migration
  pkg/migration/controllers/migration.go
  pkg/migration/controllers/migrationschedule.go
Labels: bug

#489 Use created config map for watch on mock time
  pkg/schedule/schedule.go
Labels: failing-test, integration-test

#490 Fix error with creation of stock-mock-time.
  test/integration_test/test-deploy.sh
Labels: integration-test

#498 Update test flag parsing which was broken in go 1.13
  test/integration_test/common_test.go
Labels: integration-test

#503 Update google sdk and some python packages in container
  Dockerfile
  Makefile
Labels: release-note
