Repository libopenstorage/stork, pull requests merged in 2019-07, with the labels that each got.

#412 When uploading objects don't close writer async
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#414 Allow users to specify annotation in pod if only local node should be…
  pkg/extender/extender.go
  pkg/extender/extender_test.go
Labels: enhancement, release-note

#416 Store snapshot schedule info in annotations instead of labels
  drivers/volume/portworx/portworx.go
  pkg/snapshot/controllers/snapshotschedule.go
Labels: bug

#421 Add -t to test2json to add timestamps
  test/integration_test/stork-test-pod.yaml
Labels: integration-test

#422 Validate name and namespace when generating clusterpair
  pkg/storkctl/clusterpair.go
  pkg/storkctl/clusterpair_test.go
Labels: bug

#425 Fix duplicate imports
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/applicationmanager/controllers/applicationrestore.go
  pkg/extender/extender_test.go
  pkg/migration/controllers/migration.go
  pkg/storkctl/clusterpair_test.go
  test/integration_test/common_test.go
Labels: cleanup

#420 Add API to resourcecollector package to delete objects
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/applicationmanager/controllers/applicationrestore.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#429 Add env variables to stork deployment via integration tests.
  test/integration_test/test-deploy.sh
Labels: integration-test
