Repository libopenstorage/stork, pull requests merged in 2019-09, with the labels that each got.

#456 Integration test for backup sync controller.
  test/integration_test/applicationbackup_test.go
  test/integration_test/specs/mysql-1-pvc-backup-sync/applicationbackup.yaml
  test/integration_test/specs/mysql-restore-backup-sync/applicationrestore.yaml
Labels: integration-test

#457 Create namespace mapping map in application restore if not present
  pkg/applicationmanager/controllers/applicationrestore.go
Labels: bug

#455 Convert reclaim policy to string before setting in unstructured object
  pkg/migration/controllers/migration.go
Labels: bug

#448 Add check in monitor to skip duplicate offline nodes with same IP
  drivers/volume/mock/mock.go
  drivers/volume/volume.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
Labels: bug, unit-test

#461 Don't set predicates or priorities for scheduler
  specs/stork-deployment.yaml
Labels: integration-test

#465 Use name from the existing secret object as new obj might be nil.
  test/integration_test/applicationbackup_test.go
Labels: integration-test

#463 Focus test
  test/integration_test/applicationbackup_test.go
  test/integration_test/applicationclone_test.go
  test/integration_test/clusterdomain_test.go
  test/integration_test/cmdexecutor_test.go
  test/integration_test/common_test.go
  test/integration_test/extender_test.go
  test/integration_test/health_monitor_test.go
  test/integration_test/migration_test.go
  test/integration_test/snapshot_restore_test.go
  test/integration_test/snapshot_test.go
  test/integration_test/stork-test-pod.yaml
  test/integration_test/test-deploy.sh
Labels: integration-test

#467 Create annotations for app during migration if it doesn't exist
  drivers/volume/portworx/portworx.go
  pkg/migration/controllers/migration.go
Labels: bug

#475 Check ownership of VolumeAttachment before deleting
  drivers/volume/mock/mock.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
Labels: bug

#476 Vendor update for snapshotter
  Gopkg.lock
  vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/controller/snapshot-controller/snapshot-controller.go
  vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/controller/snapshotter/snapshotter.go
Labels: bug

#477 Update the number of workers to 10 for each controller
  pkg/controller/controller.go
  pkg/migration/controllers/migration.go
Labels: bug

#459 Add migration test with startapp flag set to false
  test/integration_test/clusterdomain_test.go
  test/integration_test/migration_test.go
  test/integration_test/specs/cassandra-migration-startapps-false/migration.yaml
Labels: integration-test

#480 Fix race in migration schedule integration test
  test/integration_test/migration_test.go
Labels: failing-test, integration-test

#441 Cancel and fail backup if starting volume backup fails
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug, do-not-merge

#468 Multi cloud backup
  test/integration_test/applicationbackup_test.go
Labels: integration-test
