Repository libopenstorage/stork, pull requests merged in 2019-11, with the labels that each got.

#502 Wait backup completion
  test/integration_test/applicationbackup_test.go
Labels: integration-test

#507 enable cs inplace restore integration tests
  test/integration_test/snapshot_restore_test.go
Labels: integration-test

#509 pass poolids to Nodeid for ha update api
  drivers/volume/portworx/portworx.go
Labels: bug

#504 Updates for storkctl
  pkg/storkctl/applicationclone.go
  pkg/storkctl/applicationrestore.go
  pkg/storkctl/applicationrestore_test.go
  pkg/storkctl/snapshot.go
Labels: bug

#514 fixes for groupcsrestore
  drivers/volume/portworx/portworx.go
Labels: bug

#516 Remove call to verifySnapshot for cloudsnap test
  test/integration_test/snapshot_restore_test.go
Labels: failing-test

#519 Update vendor
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/libopenstorage/autopilot-api/LICENSE
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/register.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/v1alpha1/autopilotrule.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/v1alpha1/constants.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/v1alpha1/doc.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/v1alpha1/register.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/apis/autopilot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/doc.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/typed/autopilot/v1alpha1/autopilot_client.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/typed/autopilot/v1alpha1/autopilotrule.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/typed/autopilot/v1alpha1/doc.go
  vendor/github.com/libopenstorage/autopilot-api/pkg/client/clientset/versioned/typed/autopilot/v1alpha1/generated_expansion.go
  vendor/github.com/portworx/sched-ops/k8s/k8s.go
  vendor/github.com/portworx/torpedo/drivers/scheduler/errors.go
  vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
  vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
  vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
  vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
  vendor/github.com/portworx/torpedo/drivers/volume/volume.go
Labels: failing-test

#520 Increase timeout for backup test
  test/integration_test/applicationbackup_test.go
Labels: failing-test

#521 Rename stage in VolumeSnapshotRestore
  drivers/volume/portworx/portworx.go
  pkg/apis/stork/v1alpha1/snapshotrestore.go
  pkg/snapshot/controllers/snapshotrestore.go
Labels: cleanup

#525 [portworx] Wait for volume restore api to complete
  drivers/volume/portworx/portworx.go
  pkg/snapshot/controllers/snapshotrestore.go
Labels: bug

#522 Cleanup deleted objects from destination during migration
  Gopkg.lock
  cmd/stork/stork.go
  pkg/apis/stork/v1alpha1/migration.go
  pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/migration/controllers/migration.go
  pkg/resourcecollector/clusterrole.go
  pkg/resourcecollector/persistentvolume.go
  pkg/resourcecollector/persistentvolumeclaim.go
  pkg/resourcecollector/resourcecollector.go
  vendor/github.com/portworx/sched-ops/k8s/k8s.go
Labels: enhancement

#524 add integration test for migration cleanup feature
  test/integration_test/migration_test.go
  test/integration_test/specs/mysql-migration-schedule-interval/migrationschedule.yaml
Labels: integration-test
