Repository libopenstorage/stork, pull requests merged in 2019-05, with the labels that each got.

#354 Increase wait time in snapshotschedule test
  test/integration_test/snapshot_test.go
Labels: failing-test

#357 Vendor update for sched-ops
  Gopkg.lock
  vendor/github.com/portworx/sched-ops/k8s/k8s.go
Labels: bug

#360 Update node info to have storageID and schedulerID
  drivers/volume/mock/mock.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/extender/extender.go
  test/integration_test/common_test.go
Labels: enhancement

#351 Update google cloud sdk and use python3 in container
  Dockerfile
Labels: cleanup

#368 Fix matching of clusterdomain list
  pkg/clusterdomains/controllers/clusterdomainstatus.go
Labels: bug

#369 Add debug package to dump profiles
  cmd/stork/stork.go
  pkg/dbg/dbg.go
Labels: enhancement

#375 Add deploymentconfig to activate migrations for storkctl
  pkg/storkctl/migration.go
Labels: bug

#378 Use correct spec for extender integration test
  test/integration_test/extender_test.go
Labels: failing-test, integration-test

#371 Fix schedule to trigger if next trigger is exactly at current time
  pkg/schedule/schedule.go
  pkg/schedule/schedule_test.go
Labels: bug

#380 [Portworx] Add idempotency for local snapshots
  drivers/volume/portworx/portworx.go
Labels: bug, release-note

#383 Optimize migrations for clusterrole
  pkg/resourcecollector/clusterrole.go
  pkg/resourcecollector/resourcecollector.go
  pkg/resourcecollector/serviceaccount.go
Labels: enhancement

#385 Create some default schedule policies
  pkg/schedule/schedule.go
  pkg/schedule/schedule_test.go
  pkg/storkctl/migrationschedule.go
  pkg/storkctl/migrationschedule_test.go
Labels: enhancement, release-note

#387 Print N/A for volumes and resources when not migrating them
  pkg/storkctl/migration.go
  pkg/storkctl/migration_test.go
Labels: enhancement, release-note

#386 Set the default admin namespace to kube-system
  cmd/stork/stork.go
Labels: enhancement, release-note

#384 Add wait poll support for storkctl activate/deactivae cluster-domain
  pkg/storkctl/clusterdomainupdate.go
  pkg/storkctl/clusterdomainupdate_test.go
Labels: enhancement, release-note

#391 Add wait options for storkctl create migrations
  pkg/storkctl/migration.go
  pkg/storkctl/migration_test.go
Labels: enhancement, release-note

#390 Add suspend and resume subcommands to storkctl
  pkg/storkctl/migrationschedule.go
  pkg/storkctl/migrationschedule_test.go
  pkg/storkctl/resume.go
  pkg/storkctl/snapshotschedule.go
  pkg/storkctl/snapshotschedule_test.go
  pkg/storkctl/storkctl.go
  pkg/storkctl/suspend.go
Labels: enhancement, release-note

#394 Integration test: Use remote cluster to activate/deactivate domains
  test/integration_test/clusterdomain_test.go
Labels: integration-test
