Repository libopenstorage/stork, pull requests merged in 2020-07, with the labels that each got.

#664 Set resource version to empty before applying restored objects
  pkg/applicationmanager/controllers/applicationregistration.go
  pkg/migration/controllers/migration.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#665 Skip backup of PVCs being deleted or in Pending state
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/resourcecollector/persistentvolumeclaim.go
Labels: bug, release-note

#667 disable webhook controller by default
  cmd/stork/stork.go
Labels: bug

#673 [Portworx]: Fix updating of volume info for backup size on unsupported p…
  drivers/volume/portworx/portworx.go
Labels: bug

#678 Ignore empty pre and post exec rules
  pkg/snapshot/rule.go
Labels: bug

#679 Add some missing storage classes in integration tests
  test/integration_test/specs/elasticsearch/portworx/sc.yaml
  test/integration_test/specs/mysql-2-pvc/portworx/sc.yaml
  test/integration_test/specs/mysql-repl-1/linstor/linstor-sc.yaml
  test/integration_test/specs/mysql-repl-1/mysql.yaml
  test/integration_test/specs/mysql-repl-1/portworx/sc.yaml
Labels: integration-test

#674 Added fix to not to wait for the re-created resources in DeleteResources API.
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#686 ignore if appregistration cr is not present on cluster
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#687 Vendor update for sched-ops
  Gopkg.lock
  vendor/github.com/portworx/sched-ops/k8s/stork/applicationbackuprestore.go
Labels: integration-test

#690 [Portworx] Add check for PX version check for jwt issuer
  drivers/volume/portworx/portworx.go
Labels: feature
