Repository libopenstorage/stork, pull requests merged in 2020-03, with the labels that each got.

#566 Get the correct pluralized name of resources for the dynamic client
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#574 Integration test to delete backuplocation during app backup
  test/integration_test/applicationbackup_test.go
Labels: integration-test

#575 Integration to start app backup when another is in progress
  test/integration_test/applicationbackup_test.go
Labels: integration-test

#564 Add a reason field for the overall backup and restore status
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/applicationrestore.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/applicationmanager/controllers/applicationrestore.go
Labels: enhancement, release-note

#577 Add apt-get install jq for ubuntu base images
  test/integration_test/test-deploy.sh
Labels: integration-test

#580 Set all configmap after default config map is correctly set
  test/integration_test/applicationbackup_test.go
Labels: integration-test

#587 [portworx] Fix in-place restore failure for repl >2 vols
  drivers/volume/portworx/portworx.go
  test/integration_test/specs/mysql-cloudsnap-group-restore/mysql.yaml
  test/integration_test/specs/mysql-cloudsnap-restore/mysql.yaml
Labels: bug

#588 Update sched-ops client for all packages
  pkg/storkctl/factory.go
Labels: bug

#589 Add annotation to collect objects that have an owner reference
  pkg/resourcecollector/resourcecollector.go
Labels: feature

#590 Integration test for migration & reverse migration between two clusters
  test/integration_test/clusterdomain_test.go
  test/integration_test/common_test.go
  test/integration_test/migration_test.go
Labels: integration-test

#593 Avoid adding duplicate volume to restore status
  pkg/snapshot/controllers/snapshotrestore.go
Labels: bug
