Repository libopenstorage/stork, pull requests merged in 2020-02, with the labels that each got.

#543 Add support for gcp multi zone disks
  drivers/volume/gcp/gcp.go
  drivers/volume/portworx/portworx.go
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/applicationrestore.go
  pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
Labels: bug

#551 Remove unused status types
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/migration.go
  pkg/migration/controllers/migrationschedule.go
Labels: cleanup

#550 Change driver init error message to debug
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
  drivers/volume/portworx/portworx.go
Labels: cleanup

#553 [Azure] Store the resource group for volumes during snapshot
  drivers/volume/azure/azure.go
Labels: bug

#554 Fix duplicate tags being checked for aws driver
  drivers/volume/aws/aws.go
Labels: bug

#555 Devtest
  test/integration_test/test-deploy.sh
Labels: integration-test

#562 Vendor update for sched-ops
  Gopkg.lock
  vendor/github.com/portworx/sched-ops/k8s/core/core.go
  vendor/github.com/portworx/sched-ops/task/task.go
Labels: bug

#560 Collect CronJob objects for migration, backup and clones
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement, release-note

#559 [Portworx] Don't migrate volumes which have the skipResource annotation
  drivers/volume/portworx/portworx.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug, release-note

#565 Update applicationbackupschedule test for new retain policy
  test/integration_test/applicationbackup_test.go
Labels: failing-test, integration-test

#569 Use correct API to delete backups in test
  test/integration_test/applicationbackup_test.go
Labels: failing-test, integration-test

#571 Use correct type for length of backups in test
  test/integration_test/applicationbackup_test.go
Labels: failing-test, integration-test
