Repository libopenstorage/stork, pull requests merged in 2020-06, with the labels that each got.

#634 Use admission review request namespace to get volume info
  pkg/webhookadmission/webhook.go
Labels: bug

#639 add flag to enable/disable webhook controller
  cmd/stork/stork.go
Labels: bug

#642 Add support to collect couchbase CRs
  pkg/migration/controllers/migration.go
  pkg/resourcecollector/resourcecollector.go
  pkg/storkctl/migration.go
Labels: enhancement, release-note

#649 Disable auto-updating app scheduler as stork for app based on annotations
  cmd/stork/stork.go
  pkg/webhookadmission/webhook.go
Labels: enhancement, release-note

#650 Removed CR updates that leads to "object has be modified error".
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#653 Add applicationregistration custom resource
  pkg/apis/stork/v1alpha1/applicationregistration.go
  pkg/apis/stork/v1alpha1/register.go
  pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
  pkg/applicationmanager/applicationmanager.go
  pkg/client/clientset/versioned/typed/stork/v1alpha1/applicationregistration.go
  pkg/client/clientset/versioned/typed/stork/v1alpha1/fake/fake_applicationregistration.go
  pkg/client/clientset/versioned/typed/stork/v1alpha1/fake/fake_stork_client.go
  pkg/client/clientset/versioned/typed/stork/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/stork/v1alpha1/stork_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/stork/v1alpha1/applicationregistration.go
  pkg/client/informers/externalversions/stork/v1alpha1/interface.go
  pkg/client/listers/stork/v1alpha1/applicationregistration.go
  pkg/client/listers/stork/v1alpha1/expansion_generated.go
Labels: feature

#652 Add support for restoring specific objects
  drivers/volume/portworx/portworx.go
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/applicationrestore.go
  pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/applicationmanager/controllers/applicationrestore.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement, release-note
