Repository libopenstorage/stork, pull requests merged in 2020-04, with the labels that each got.

#595 Check if schedule policy exists in cache
  pkg/schedule/cache.go
Labels: bug

#599 Explicitly reset kubeconfig after every migration-backup loop
  test/integration_test/migration_backup_test.go
Labels: integration-test

#602 [AWS] Add backoff for snapshot API in case rates limit is hit
  drivers/volume/aws/aws.go
Labels: bug

#603 Integration test for application backup of a migrated app
  test/integration_test/applicationbackup_test.go
  test/integration_test/clusterdomain_test.go
  test/integration_test/common_test.go
  test/integration_test/migration_backup_test.go
  test/integration_test/migration_test.go
Labels: integration-test

#608 [AWS] Retry snaps for internal errors
  drivers/volume/aws/aws.go
Labels: bug

#607 During restore skip resources from namespaces that aren't provided in…
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/applicationmanager/controllers/applicationrestore.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#610 Fix pre exec rule failure in application backup
  drivers/volume/portworx/portworx.go
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#612 Allow drivers to return resources that should be restored before volumes
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/applicationmanager/controllers/applicationrestore.go
Labels: bug, release-note

#614 Don't block driver registration if init fails
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
  drivers/volume/portworx/portworx.go
Labels: bug

#615 During backup skip PVCs with unsupported drivers
  drivers/volume/volume.go
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug
