Repository libopenstorage/stork, pull requests merged in 2020-08, with the labels that each got.

#692 allow string type for appreg suspend option
  pkg/apis/stork/v1alpha1/applicationregistration.go
  pkg/applicationmanager/controllers/applicationregistration.go
  pkg/migration/controllers/migration.go
  pkg/storkctl/applicationregistration.go
  pkg/storkctl/migration.go
Labels: enhancement

#694 Add support to collect LimitRange for Migration/ApplicationBackup/Clone
  pkg/resourcecollector/resourcecollector.go
Labels: release-note

#698 ResourceCollector: When checking for resources set group name for core
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#703 Computing total backup size before uploading metadata.json file
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#696 Added check for Notfound error in GetRestoreStatus of all driver.
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
Labels: bug

#699 Passing empty endpoint to AWS objectstore operations
  pkg/objectstore/s3/s3.go
Labels: enhancement

#701 Fix to populate backup and restore size for azure volumes
  drivers/volume/azure/azure.go
Labels: bug

#702 Adding actual backup size in backup volume info
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
  drivers/volume/portworx/portworx.go
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/applicationrestore.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/applicationmanager/controllers/applicationrestore.go
Labels: enhancement

#706 Add support to specify resources during application backup
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/applicationmanager/controllers/applicationclone.go
  pkg/applicationmanager/controllers/applicationrestore.go
  pkg/migration/controllers/migration.go
  pkg/resourcecollector/persistentvolume.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement, release-note
