Repository libopenstorage/stork, pull requests merged in 2021-06, with the labels that each got.

#835 Migrate updated PVC specs each time
  pkg/migration/controllers/migration.go
Labels: bug, release-note

#842 Fix namespaced schedule policy cache watch list
  pkg/schedule/cache.go
Labels: bug

#843 Skipping backing up of gke-resource-quotas
  pkg/resourcecollector/resourcecollector.go
  pkg/resourcecollector/resourcequota.go
Labels: bug

#846 Add a new annotation to skip PVCs from stork's scheduler scoring algorithm
  drivers/volume/mock/mock.go
  drivers/volume/portworx/portworx.go
  pkg/extender/extender.go
  pkg/extender/extender_test.go
  pkg/monitor/monitor_test.go
Labels: feature

#841 Backing up NetworkPolicy and PodDisruptionBudget objects
  pkg/resourcecollector/networkpolicy.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement, release-note

#852 Backing up selected resource and all resoucres of given namespace
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement

#853 Allow setting k8s client api rate limiter
  cmd/stork/stork.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement, release-note
