Repository libopenstorage/stork, pull requests merged in 2021-01, with the labels that each got.

#777 stor:335 Adding batch processing logic in passing namespace list to the GetResources API of resourceCollector pkg
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#780 [cherry-pick 2.6] Passing namespace list in batches to resourceCollector.GetResources()
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#779 Explicitly add linux as the GOOS
  Makefile
Labels: cleanup

#782 Fixed the issue in updating volumeInfo, when all volumes are successful.
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#781 [Portworx]: Setting backup size to zero on failure when fetching size
  drivers/volume/portworx/portworx.go
Labels: bug

#784 stor-338: Corrected the error handling, while calling CloudBackupCreate api.
  drivers/volume/portworx/portworx.go
Labels: bug

#783 Create pvc objects if volumeOnly migration is enabled
  pkg/migration/controllers/migration.go
Labels: enhancement
