Repository libopenstorage/stork, pull requests merged in 2021-03, with the labels that each got.

#800 Updating clusterIps field of service to nil in prepareServiceResourceForCollection.
  pkg/resourcecollector/service.go
Labels: bug

#803 [cherry-pick: 2.6] Updating clusterIps field of service to nil in prepareServiceResourceForCollection
  pkg/resourcecollector/service.go
Labels: bug

#799 Adding support for fetching resources based on requested resource types
  pkg/apis/stork/v1alpha1/applicationbackup.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement

#798 Added logic to exclude the controlled resources from GetResources API.
  pkg/resourcecollector/configmap.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#807 [cherry-pick:2.6] Added logic to exclude the controlled resources from GetResources API.
  pkg/resourcecollector/configmap.go
  pkg/resourcecollector/resourcecollector.go
Labels: bug

#802 configure side-effect parameter for stork webhook
  pkg/webhookadmission/utils.go
  pkg/webhookadmission/webhook.go
Labels: bug

#787 Add storkctl option to create reverse cluster pairing
  pkg/storkctl/clusterpair.go
  pkg/storkctl/create.go
Labels: enhancement, release-note

#792 Detect newly registered crd and create appreg entry in stork
  pkg/applicationmanager/controllers/applicationregistration.go
Labels: enhancement

#810 prometheus alerts for stork metrics
  specs/prometheus/rule.yaml
Labels: documentation

#811 Add appreg suspend support for CR's
  pkg/appregistration/appregistration.go
Labels: enhancement

#815 Clusterpair failure tests
  test/integration_test/common_test.go
  test/integration_test/migration_test.go
Labels: integration-test
