Repository libopenstorage/stork, pull requests merged in 2022-08, with the labels that each got.

#1138 pb-3002: call v1 version CRD API for k8s 1.22 or more.
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug

#1137 PWX-26192: Add controller for Resourcetransformation CR
  pkg/log/log.go
  pkg/migration/controllers/migration.go
  pkg/migration/controllers/resourcetransformation.go
  pkg/migration/migration.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement

#1131 PWX-24851: Enhance UX experience for setting up clusterpair for async-DR
  pkg/storkctl/clusterpair.go
Labels: enhancement, in-progress
