Repository libopenstorage/stork, pull requests merged in 2022-10, with the labels that each got.

#1168 PWX-26934: Handle panic for SkipDeletedNamespace flag
  pkg/migration/controllers/migration.go
Labels: bug

#1174 PWX-27136: Do not collect VirtualMachineInstanceMigration CR.
  pkg/resourcecollector/resourcecollector.go
  pkg/resourcecollector/virtualmachineinstance.go
Labels: enhancement

#1190 PWX-27094: User friendly message if transformation spec is not in ready state
  pkg/migration/controllers/migration.go
Labels: bug

#1189 PB-3150: Handle GCE snapshot NotFound error in DeleteBackup
  drivers/volume/gcp/gcp.go
Labels: release-note

#1192 Handle checks for resource transformation spec paths
  pkg/migration/controllers/resourcetransformation.go
  pkg/resourcecollector/resourcetransformation.go
  pkg/schedule/schedule.go
Labels: bug
