Repository libopenstorage/stork, pull requests merged in 2022-03, with the labels that each got.

#1049 PD-1108 update app spec example
  specs/mysql.yaml
Labels: documentation

#1050 Allow to run complete integration suite
  test/integration_test/common_test.go
  test/integration_test/extender_test.go
  test/integration_test/migration_failover_failback_test.go
  test/integration_test/migration_test.go
Labels: integration-test

#1060 [PB-2194]: backuplocation object to have crdential info associated with the cluster.
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gcp/gcp.go
  go.mod
  go.sum
  pkg/apis/stork/v1alpha1/backuplocation.go
  test/integration_test/webhook_test.go
  vendor/github.com/portworx/sched-ops/k8s/stork/backuplocation.go
  vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
  vendor/modules.txt
Labels: enhancement

#1063 Upgrade openssl libs
  Dockerfile
Labels: bug
