Repository libopenstorage/stork, pull requests merged in 2022-02, with the labels that each got.

#1036 Always sync volumesnapshotschedule and volumesnapshot status
  pkg/snapshot/controllers/snapshotschedule.go
Labels: bug, release-note

#1037 Replace sysbench with fio
  test/integration_test/applicationbackup_test.go
  test/integration_test/specs/mysql-fio/fio-config-map.yaml
  test/integration_test/specs/mysql-fio/fio.yaml
  test/integration_test/specs/mysql-fio/pxd/px-storage-class.yaml
  test/integration_test/specs/mysql-prepare/prepare.yaml
  test/integration_test/specs/mysql-verify/verify.yaml
Labels: do-not-merge

#1045 pwx-22958: Fix faling integration-test
  test/integration_test/extender_test.go
  test/integration_test/migration_test.go
  test/integration_test/specs/mysql-migration-schedule-interval-autosuspend/migrationschedule.yaml
  test/integration_test/specs/mysql-migration-schedule-interval-autosuspend/schedulepolicy.yaml
Labels: integration-test

#1047 pb-2178: Obtain object-lock info for S3 bucket
  pkg/objectstore/s3/s3.go
Labels: enhancement
