Repository libopenstorage/stork, pull requests merged in 2023-11, with the labels that each got.

#1541 PWX-32199: Improvements to storkctl cli create migration schedule
  pkg/storkctl/migrationschedule.go
  pkg/storkctl/migrationschedule_test.go
Labels: enhancement, unit-test

#1552 PB-4632: Skip Default Kubernetes Endpoint
  pkg/resourcecollector/endpoint.go
Labels: release-note

#1532 PB-4564: unmarshalling error when RT transform spec path type is int/bool
  pkg/resourcecollector/resourcetransformation.go
Labels: bug

#1560 PWX-34118: Skip service accounts, roles and rolebindings as part of pruning of resources with ownerreferences.
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement

#1562 [PWX-34708] Support multi-DR for normal application resources and CRs with suspend options
  pkg/migration/controllers/migration.go
Labels: bug, release-note

#1554 PWX-31058: Supporting exclude resource types in migration.
  pkg/apis/stork/v1alpha1/migration.go
  pkg/migration/controllers/migration.go
  pkg/resourcecollector/resourcecollector.go
Labels: enhancement

#1561 [PWX-34809] Adding the remaining params to storkctl create migrationschedule
  pkg/storkctl/migrationschedule.go
  pkg/storkctl/migrationschedule_test.go
Labels: enhancement, release-note, unit-test

#1530 PB-4598: Fix for Stork pods crash issue if the RT CR using the a transform of type slice and operation add
  pkg/resourcecollector/resourcetransformation.go
Labels: bug

#1551 [PWX-32336]: adding integration tests for validating storkctl create migrationschedule changes
  test/integration_test/common_test.go
  test/integration_test/specs/storkctl-specs/migrationschedule/custom-async-migration-schedule.yaml
  test/integration_test/specs/storkctl-specs/migrationschedule/custom-sync-migration-schedule.yaml
  test/integration_test/specs/storkctl-specs/migrationschedule/default-async-migration-schedule.yaml
  test/integration_test/specs/storkctl-specs/migrationschedule/default-sync-migration-schedule.yaml
  test/integration_test/storkctl_migrationschedule_test.go
  test/integration_test/storkctl_schedulepolicy_test.go
Labels: integration-test
