Repository libopenstorage/stork, pull requests merged in 2023-08, with the labels that each got.

#1470 PWX-28210: Disable filter and prioritize for Windows Pods
  drivers/volume/mock/mock.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/extender/extender.go
  pkg/extender/extender_test.go
  pkg/monitor/monitor_test.go
Labels: release-note, unit-test

#1471 PWX-32425: Non-managed Replicaset activating/deactivating with storkctl.
  pkg/resourceutils/updatereplicas.go
  pkg/storkctl/migration_test.go
Labels: enhancement, release-note, unit-test

#1474 PB-4193: Portworx volume size issue
  drivers/volume/portworx/portworx.go
Labels: bug

#1451 PWX-31470: Clusterwide operator CR migration support.
  pkg/apis/stork/v1alpha1/applicationregistration.go
  pkg/migration/controllers/clusterpair.go
  pkg/migration/controllers/migration.go
  pkg/resourceutils/updatereplicas.go
  pkg/utils/utils.go
Labels: enhancement, documentation, release-note

#1486 PWX-31372: storkctl to support backing up specific resource types and restoring specific objects.
  pkg/storkctl/applicationbackup.go
  pkg/storkctl/applicationbackup_test.go
  pkg/storkctl/applicationrestore.go
  pkg/storkctl/applicationrestore_test.go
  pkg/storkctl/common.go
Labels: enhancement, documentation
