Repository libopenstorage/stork, pull requests merged in 2024-07, with the labels that each got.

#1804 chore: upgrade go to v1.21.11 for cve fix
  Makefile
Labels: security

#1807 chore: upgrade aws-authenticator and gcloud-cli to latest version
  Dockerfile
Labels: in-progress, security

#1810 PWX-38021: Creation of mutatingwebhook after each leader election.
  cmd/stork/stork.go
  pkg/webhookadmission/utils.go
Labels: bug

#1815 test: increase timeouts in integration tests
  test/integration_test/common_test.go
  test/integration_test/migration_test.go
Labels: test
