Repository libopenstorage/stork, pull requests merged in 2024-02, with the labels that each got.

#1602 PB-4991: Update ApplicationBackupController to execute the post-exec …
  pkg/applicationmanager/controllers/applicationbackup.go
Labels: bug, release-note

#1624 [PWX-34896] Only suspend migrationSchedules which are involved in migrating the namespaces being activated
  pkg/resourcecollector/resourcecollector.go
  pkg/storkctl/common_test.go
  pkg/storkctl/migration.go
  pkg/storkctl/migration_test.go
  pkg/storkctl/migrationschedule.go
Labels: bug, unit-test

#1626 PB-5434, PB-5559 : Refining Backup Variants
  .gitignore
  drivers/volume/csi/csi.go
  drivers/volume/kdmp/kdmp.go
  drivers/volume/volume.go
  pkg/applicationmanager/controllers/applicationbackup.go
  pkg/snapshotter/options.go
  pkg/snapshotter/snapshotter_csi.go
Labels: enhancement, release-note, feature
