Repository libopenstorage/stork, pull requests merged in 2024-09, with the labels that each got.

#1839 PWX-38559: clean errored out snapshot cr older than a certain time period
  Makefile
  pkg/apis/stork/v1alpha1/volumesnapshotschedule.go
  pkg/snapshot/controllers/snapshot.mock.go
  pkg/snapshot/controllers/snapshotschedule.go
  pkg/snapshot/controllers/snapshotschedule_test.go
  pkg/storkctl/common_test.go
Labels: bug

#1841 pwx-38383: make the controller cache sync timeout configurable
  cmd/stork/stork.go
Labels: improvement

#1851 PWX-36167: Duplicate offline nodes should be excluded for pod eviction if another online node exists with same scheduler ID.
  drivers/volume/volume.go
  pkg/monitor/monitor_test.go
Labels: bug, unit-test

#1852 PWX-39128: Support env variable SKIP_AWS_DRIVER_INIT to skip the aws driver init in stork.
  drivers/volume/aws/aws.go
Labels: enhancement
