Repository libopenstorage/stork, pull requests merged in 2024-08, with the labels that each got.

#1823 pwx-38027: test for modifying retain values in schedule policy of snapshotschedule
  test/integration_test/snapshot_test.go
Labels: integration-test

#1806 pwx-37111: add stork argument to disable preloading statfs
  cmd/stork/stork.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/webhookadmission/webhook.go
Labels: improvement

#1831 PWX-38560: add wait for fetching destination volume id in dataExportTest CBT
  test/integration_test/common_test.go
  test/integration_test/dataexport_rsync_test.go
Labels: improvement

#1829 PWX-37811: Ignoring witness node during clusterdomain activate/deactivate with failover/failback.
  Makefile
  drivers/volume/mock/volume/driver.mock.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/action/drutils.go
  pkg/action/drutils_test.go
Labels: bug

#1837 pwx-38748: upgrade gcloud-sdk version to fix crc32 vuln
  Dockerfile
Labels: security
