Repository libopenstorage/stork, pull requests merged in 2024-03, with the labels that each got.

#1665 PWX-35885: Doing update on latest copy of volumesnapshotschedule to avoid update failures not happening on latest version.
  pkg/snapshot/controllers/snapshotschedule.go
Labels: enhancement

#1678 PWX-36622: Optimize stork image by removing unused contents from google-cloud-sdk.
  Dockerfile
Labels: enhancement

#1666 [PWX-35853] Failover Controller all stages
  pkg/action/actioncontroller.go
  pkg/action/failback.go
  pkg/action/failover.go
  pkg/storkctl/action.go
  pkg/utils/utils.go
Labels: feature

#1686 PWX-35626: Add a last 4 digit UID string from volumesnapshotschedule to volumesnapshot name to avoid name collision.
  pkg/snapshot/controllers/snapshotschedule.go
  test/integration_test/snapshot_test.go
Labels: bug, integration-test
